name: Ballerina Dependabot
on: 
  workflow_dispatch:
jobs:
  resolve_dependencies:
    runs-on: ubuntu-latest
    name: Dependabot
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependabot Action
        uses: TharindaDilshan/ballerina-dependabot-extended@main
        id: bot
        with:
          git_email: ${{ secrets.BALLERINA_BOT_EMAIL }}
          git_username: ${{ secrets.BALLERINA_BOT_USERNAME}}
          token: ${{ secrets.BALLERINA_BOT_TOKEN }}
